#version 460
#define __COMP__

#extension GL_GOOGLE_include_directive: require
#include "common.glsl"

struct DrawMeshTasksIndirectCommand
{
    uint32 workGroupsX;
    uint32 workGroupsY;
    uint32 workGroupsZ;

    uint32 objectId; // Index into the object data buffer
};

layout (buffer_reference, scalar) writeonly buffer IndirectCommandBuffer { DrawMeshTasksIndirectCommand commands[]; };
layout (buffer_reference, scalar) writeonly buffer CountBuffer { uint32 count; };

layout (push_constant) uniform PushData
{
    CameraBuffer cameraBuffer;
    ObjectDataBuffer objectDataBuffer;
    TransformDataBuffer transformBuffer;
    MeshMetadataBuffer meshMetadataBuffer;
    IndirectCommandBuffer indirectBuffer;
    CountBuffer countBuffer;

    uint32 activeObjectCount;
} pcs;

layout (local_size_x = 32u) in;

bool isVisible(float3 p_center, float p_radius)
{
    for (uint32 i = 0u; i < 6u; ++i)
    {
        if (dot(pcs.cameraBuffer.frustumPlanes[i].xyz, p_center) + pcs.cameraBuffer.frustumPlanes[i].w < -p_radius)
        {
            return false;
        }
    }
    return true;
}

void main()
{
    uint32 global_id = gl_GlobalInvocationID.x;

    if (global_id >= pcs.activeObjectCount)
    {
        return;
    }

    ObjectData obj_data = pcs.objectDataBuffer.data[global_id];
    MeshMetadata metadata = pcs.meshMetadataBuffer.metadata[obj_data.meshId];

    float4x4 model = pcs.transformBuffer.data[obj_data.transformId];
    float3 center = (model * float4(metadata.boundingSphere.xyz, 1.0f)).xyz;
    float max_scale = max(length(model[0u].xyz), max(length(model[1u].xyz), length(model[2u].xyz)));
    float radius = metadata.boundingSphere.w * max_scale;

    if (isVisible(center, radius))
    {
        uint32 command_index = atomicAdd(pcs.countBuffer.count, 1u);

        pcs.indirectBuffer.commands[command_index].workGroupsX = (metadata.meshletCount + WARP_SIZE - 1u) / WARP_SIZE;
        pcs.indirectBuffer.commands[command_index].workGroupsY = 1u;
        pcs.indirectBuffer.commands[command_index].workGroupsZ = 1u;
        pcs.indirectBuffer.commands[command_index].objectId = global_id;
    }
}